version: "3.7"

networks:
    frontend:
      driver: bridge
    
    backend:
      driver: bridge

services:

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    links:
      - php
    volumes:
      - ./www:/var/www
      - ./nginx/hosts/site.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs/nginx-access.log:/var/log/nginx/access.log
      - ./nginx/logs/nginx-error.log:/var/log/nginx/error.log
    networks:
      - frontend
      - backend
    container_name: nginx

  php:
    image: php:fpm
    ports:
      - "9000:9000"
    networks:
      - backend
    volumes:
      - ./www:/var/www
    depends_on:
      - postgres
    container_name: fpm

  postgres:
    image: postgres:alpine
    volumes:
      - ./postgresql/data/:/var/lib/postgresql/
    environment:
      - POSTGRES_ROOT_PASSWORD=root
      - POSTGRES_DB=local
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "3306:3306"
    networks:
      - backend
    container_name: postgres

  adm:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - frontend
      - backend
    container_name: adm